# Generated by Django 3.2.14 on 2022-08-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('name_user', models.CharField(max_length=64)),
            ],
        ),
    ]
